
   
import type { NextPage } from "next";
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
   <>

<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik&display=swap"
          rel="stylesheet"
          />
      </Head>

      <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>
   </>
      

      

  )
}
export default Home;